In [26]:
import pandas as pd
上海=pd.read_excel('d:/mydoc/code/jupyter/销量统计.xlsx','上海销量',header=1,index_col=0)
上海

      1月   2月   3月   4月   5月   6月
按摩椅  104  177  189  156  121  126
针灸仪  146  131  179  193  190  125
诊疗仪  152  106  109  168  174  143
消毒柜  178  130  189  164  133  156

In [29]:
深圳=pd.read_excel('d:/mydoc/code/jupyter/销量统计.xlsx','深圳销量',header=1,index_col=0)
深圳

      1月   2月   3月   4月   5月   6月
消毒柜  197  179  183  147  137  140
按摩椅  102  128  124  132  178  196
诊疗仪  138  115  175  152  189  142
针灸仪  160  123  132  170  183  172

In [69]:
调货=pd.read_excel('d:/mydoc/code/jupyter/销量统计.xlsx','调货明细',header=0)
调货

                  调货时间   品名  数量 接收单位
0  2021-01-03 00:00:00  按摩椅   2   广州
1  2021-01-03 04:51:00  诊疗仪   2   广州
2  2021-01-03 12:12:00  针灸仪   1   深圳
3  2021-01-03 17:10:00  针灸仪   1   上海
4  2021-01-04 05:10:00  诊疗仪   2   深圳
5  2021-01-04 22:10:00  针灸仪   2   广州
6  2021-01-05 09:56:00  针灸仪   1   深圳
7  2021-01-05 10:59:00  消毒柜   2   上海
8  2021-01-06 10:55:00  针灸仪   2   深圳
9  2021-01-07 00:18:00  按摩椅   2   深圳
10 2021-01-07 22:35:00  针灸仪   1   上海
11 2021-01-07 23:56:00  诊疗仪   1   广州
12 2021-01-08 18:16:00  诊疗仪   2   广州
13 2021-01-09 12:38:00  消毒柜   1   深圳
14 2021-01-01 05:21:00  针灸仪   1   广州
15 2021-01-01 10:03:00  按摩椅   2   深圳
16 2021-01-11 21:55:00  按摩椅   2   上海

In [89]:
值班=pd.read_excel('d:/mydoc/code/jupyter/销量统计.xlsx','值班记录',header=0,index_col=0)
值班

           仓库地点 值班人员
值班日期
2021-01-01   上海   李四
2021-01-01   广州   王五
2021-01-01   深圳   刘八
2021-01-02   上海   张三
2021-01-02   广州   王五
2021-01-02   深圳   田七
2021-01-03   上海   张三
2021-01-03   广州   赵六
2021-01-03   深圳  NaN
2021-01-04   上海   张三
2021-01-04   广州   赵六
2021-01-04   深圳  NaN
2021-01-05   上海   张三
2021-01-05   广州   王五
2021-01-05   深圳   刘八
2021-01-06   上海  NaN
2021-01-06   广州   赵六

In [30]:
上海+深圳

      1月   2月   3月   4月   5月   6月
按摩椅  206  305  313  288  299  322
消毒柜  375  309  372  311  270  296
诊疗仪  290  221  284  320  363  285
针灸仪  306  254  311  363  373  297

In [76]:
调货['调货时间'] = pd.to_datetime(调货['调货时间'])
调货_索引 = 调货.sort_values('调货时间').set_index('调货时间')
re = 调货_索引['2021-1-4 12:00':'2021-1-8'][调货_索引['品名']=='针灸仪']
re

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16244\66106925.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  re = 调货_索引['2021-1-4 12:00':'2021-1-8'][调货_索引['品名']=='针灸仪']

                      品名  数量 接收单位
调货时间
2021-01-04 22:10:00  针灸仪   2   广州
2021-01-05 09:56:00  针灸仪   1   深圳
2021-01-06 10:55:00  针灸仪   2   深圳
2021-01-07 22:35:00  针灸仪   1   上海

In [81]:
调货_索引[调货_索引.index.hour==0]

                      品名  数量 接收单位
调货时间
2021-01-03 00:00:00  按摩椅   2   广州
2021-01-07 00:18:00  按摩椅   2   深圳

In [85]:
daynum=调货_索引.groupby(调货_索引.index.date).agg(sum)
daynum

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16244\1717248463.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  daynum=调货_索引.groupby(调货_索引.index.date).agg(sum)

                      品名  数量      接收单位
2021-01-01        针灸仪按摩椅   3      广州深圳
2021-01-03  按摩椅诊疗仪针灸仪针灸仪   6  广州广州深圳上海
2021-01-04        诊疗仪针灸仪   4      深圳广州
2021-01-05        针灸仪消毒柜   3      深圳上海
2021-01-06           针灸仪   2        深圳
2021-01-07     按摩椅针灸仪诊疗仪   4    深圳上海广州
2021-01-08           诊疗仪   2        广州
2021-01-09           消毒柜   1        深圳
2021-01-11           按摩椅   2        上海

In [88]:
调货_索引['日期']=调货_索引.index.date
调货_索引

                      品名  数量 接收单位          日期
调货时间
2021-01-01 05:21:00  针灸仪   1   广州  2021-01-01
2021-01-01 10:03:00  按摩椅   2   深圳  2021-01-01
2021-01-03 00:00:00  按摩椅   2   广州  2021-01-03
2021-01-03 04:51:00  诊疗仪   2   广州  2021-01-03
2021-01-03 12:12:00  针灸仪   1   深圳  2021-01-03
2021-01-03 17:10:00  针灸仪   1   上海  2021-01-03
2021-01-04 05:10:00  诊疗仪   2   深圳  2021-01-04
2021-01-04 22:10:00  针灸仪   2   广州  2021-01-04
2021-01-05 09:56:00  针灸仪   1   深圳  2021-01-05
2021-01-05 10:59:00  消毒柜   2   上海  2021-01-05
2021-01-06 10:55:00  针灸仪   2   深圳  2021-01-06
2021-01-07 00:18:00  按摩椅   2   深圳  2021-01-07
2021-01-07 22:35:00  针灸仪   1   上海  2021-01-07
2021-01-07 23:56:00  诊疗仪   1   广州  2021-01-07
2021-01-08 18:16:00  诊疗仪   2   广州  2021-01-08
2021-01-09 12:38:00  消毒柜   1   深圳  2021-01-09
2021-01-11 21:55:00  按摩椅   2   上海  2021-01-11

In [92]:
值班['日期']=值班.index.date
值班

           仓库地点 值班人员          日期
值班日期
2021-01-01   上海   李四  2021-01-01
2021-01-01   广州   王五  2021-01-01
2021-01-01   深圳   刘八  2021-01-01
2021-01-02   上海   张三  2021-01-02
2021-01-02   广州   王五  2021-01-02
2021-01-02   深圳   田七  2021-01-02
2021-01-03   上海   张三  2021-01-03
2021-01-03   广州   赵六  2021-01-03
2021-01-03   深圳  NaN  2021-01-03
2021-01-04   上海   张三  2021-01-04
2021-01-04   广州   赵六  2021-01-04
2021-01-04   深圳  NaN  2021-01-04
2021-01-05   上海   张三  2021-01-05
2021-01-05   广州   王五  2021-01-05
2021-01-05   深圳   刘八  2021-01-05
2021-01-06   上海  NaN  2021-01-06
2021-01-06   广州   赵六  2021-01-06

In [100]:
all=pd.merge(调货_索引,值班,left_on=['日期','接收单位'],right_on=['日期','仓库地点'],how='left')
all

     品名  数量 接收单位          日期 仓库地点 值班人员
0   针灸仪   1   广州  2021-01-01   广州   王五
1   按摩椅   2   深圳  2021-01-01   深圳   刘八
2   按摩椅   2   广州  2021-01-03   广州   赵六
3   诊疗仪   2   广州  2021-01-03   广州   赵六
4   针灸仪   1   深圳  2021-01-03   深圳  NaN
5   针灸仪   1   上海  2021-01-03   上海   张三
6   诊疗仪   2   深圳  2021-01-04   深圳  NaN
7   针灸仪   2   广州  2021-01-04   广州   赵六
8   针灸仪   1   深圳  2021-01-05   深圳   刘八
9   消毒柜   2   上海  2021-01-05   上海   张三
10  针灸仪   2   深圳  2021-01-06  NaN  NaN
11  按摩椅   2   深圳  2021-01-07  NaN  NaN
12  针灸仪   1   上海  2021-01-07  NaN  NaN
13  诊疗仪   1   广州  2021-01-07  NaN  NaN
14  诊疗仪   2   广州  2021-01-08  NaN  NaN
15  消毒柜   1   深圳  2021-01-09  NaN  NaN
16  按摩椅   2   上海  2021-01-11  NaN  NaN